INSERT INTO economic_sectors (sector_name) VALUES
('Agricultura, Silvicultura y Pesca'),
('Extracción de Minerales y Cantería'),
('Manufactura'),
('Suministro de Electricidad, Gas, Vapor y Aire Acondicionado'),
('Suministro de Agua; Alcantarillado, Gestión de Residuos y Remedios'),
('Construcción'),
('Comercio al por Mayor y al por Menor; Reparación de Vehículos Automotores y Motocicletas'),
('Transporte y Almacenamiento'),
('Actividades de Alojamiento y Servicio de Comidas'),
('Información y Comunicaciones'),
('Actividades Financieras y de Seguros'),
('Actividades Inmobiliarias'),
('Servicios Profesionales, Científicos y Técnicos'),
('Actividades de Servicios Administrativos y de Apoyo'),
('Administración Pública y Defensa; Seguridad Social Obligatoria'),
('Educación'),
('Actividades de Salud Humana y Trabajo Social'),
('Artes, Entretenimiento y Recreación'),
('Otras Actividades de Servicios');